[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [{ access = "read-write", path = "./"},{ access = "read-write", path = "/tmp/"}]
ffi = true

[profile.remappings]
# ds-test = "lib/forge-std/lib/ds-test/src/"
forge-std = "lib/foundry-noir-helper/lib/forge-std/src/"
# foundry-noir-helper = "lib/foundry-noir-helper/src/"

[rpc_endpoints]
educhain-testnet = { url = "${EDU_CHAIN_TESTNET_RPC}", chain = "educhain-testnet" }
#sepolia = "${SEPOLIA_RPC}"

[etherscan]
educhain-testnet = { key = "${EDU_CHAIN_TESTNET_PRIVATE_KEY}", url = "https://api.educhain-testnet.org/api" }
#sepolia = { key = "${SEPOLIA_PRIVATE_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
